<?php
/** @var \McLane\Store\Block\Cart $block */
?>
<div class="mclane-store-block-cart">
    <h3><?= __('Your Cart') ?></h3>
    <?php if ($block->showCart()): ?>
        CART SVG
        <p><?= __('Your truck is $1 full', 70) ?></p>
        <small><?= __('Max one truck per order.') ?></small>
    <?php endif ?>
    <?php //print $block->getBlockHtml('') ?>
    <?php //print $block->getBlockHtml('') ?>
</div>
