<?php
/** @var \McLane\Store\Block\Store $block */
?>
<p><?= __('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam in scelerisque erat. Vestibulum ante ipsum primis.') ?></p>
<?php foreach ($block->getStores() as $store): ?>
    <a href="<?= $block->escapeUrl($store['url']) ?>" title="<?= $block->escapeHtmlAttr($store['name']) ?>" class="rounded">
        <i class="fa fa-archive"></i>
        <?= $block->escapeHtml($store['name']) ?>
    </a>
<?php endforeach ?>
