<?php
/** @var \McLane\Store\Block\SwitchStore $block */
?>
<div class="store-change float-left">
    <span><?= $block->getCurrentStore() ?></span>
    <div class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <?= __('Change') ?>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <?php foreach ($block->getStores() as $store): ?>
                <a class="dropdown-item" href="<?= $store['url'] ?>">
                    <?= $block->escapeHtml($store['name']) ?>
                </a>
            <?php endforeach ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    ".dropdown-item": {
        "McLane_Store/js/abandoned-cart": {
            "title": "<?= $block->escapeHtml(__('Are you sure you want to leave your cart?')) ?>",
            "content": "<?= $block->escapeHtml(__('You still have items and will lose them. Continue?')) ?>"
        }
    }
}
</script>
