<?php
/** @var \McLane\Store\Block\SwitchStore $block */
?>
<div class="store-change float-left">
    <span><?= $block->getCurrentStore() ?></span>
    <div class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <?= __('Change') ?>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </div>
</div>
