<?php
/** @var $block \McLane\Store\Block\Cart */
?>
<?php if ($this->helper('McLane\User\Helper\Data')->isCustomerLoggedIn()): ?>
<div class="mclane-store-block-cart">
    <h3><?= __('Your Cart') ?></h3>
    <?php if ($block->showCart()): ?>
        CART SVG
        <p><?= __('Your truck is $1 full', 70) ?></p>
        <small><?= __('Max one truck per order.') ?></small>
    <?php endif ?>
    <?php print $block->getBlockHtml('mclane.store.cart.items') ?>
    <?php print $block->getBlockHtml('mclane.store.cart.subtotal') ?>
    <a href="<?= $this->getUrl('checkout') ?>"><?= __('Check Out') ?></a>
</div>
<?php endif ?>
