<?php
/** @var \Magento\Framework\View\Element\Template $block */

$viewModel = $block->getData('viewModel');
?>
<div data-bind="scope: 'mclane_store_cart_subtotal'">
    <p><?= __('Delivery Fee:') ?> Sales rep will contact you</p>
    <!-- ko if: cart.hasSubtotal -->
    <p>
        <strong><?= __('Subtotal:') ?> <span data-bind="html: cart.price"></span></strong>
    </p>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "mclane_store_cart_subtotal": {
                    "component": "McLane_Store/js/cart-subtotal",
                    "cart": <?= $viewModel->getSubtotal() ?>
                }
            }
        }
    }
}
</script>
