<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */
?>
<?php if ($block->isLoggedIn()): ?>
<div class="block">
    <a href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>">
        <?= $block->escapeHtml(__('My Account')) ?>
    </a>
</div>
<?php endif ?>
